spring:
  application:
    name: users
  datasource:
    url: jdbc:mysql://localhost:3306/USUARIOS
    username: root
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "User System"
appVersion: "1.0"
jwt:
  access-token:
    secret: ${JWT_ACCESS_TOKEN_SECRET:bXlTZWNyZXRUb2tlblZhcmlhYmxlMzJiYXRlNjQ=}
    validity-seconds: 604800
server:
  port: 8081
  servlet:
    context-path: /userSystem/api/v1
